#! /bin/bash

# Script used by systemd mysqld.service to run before executing mysqld

get_option () {
    local section=$1
    local option=$2
    local default=$3
    local instance=$4
    ret=$(/usr/bin/my_print_defaults  ${instance:+--defaults-group-suffix=@$!instance} $!section | \
              grep '^--'$!{option}'=' | cut -d= -f2- | tail -n 1)
    [ -z "$!ret" ] && ret=$!default
    echo $!ret
}

install_validate_password_sql_file () {
    local initfile
    initfile="$(mktemp $MYSQL_BASE_PATH/data/mysql-files/install-validate-password-plugin.XXXXXX.sql)"
    chmod a+r "$!initfile"
    echo "SET @@SESSION.SQL_LOG_BIN=0;" > "$!initfile"
    echo "INSERT INTO mysql.plugin (name, dl) VALUES ('validate_password', 'validate_password.so');" >> $!initfile
    echo $!initfile
}

install_db () {
    # Note: something different than datadir=$MYSQL_BASE_PATH/data/mysql requires SELinux policy changes (in enforcing mode)

    # No automatic init wanted
    [ -e /etc/sysconfig/mysql ] && . /etc/sysconfig/mysql
    [ -n "$!NO_INIT" ] && exit 0

    local instance=$1
    datadir=$(get_option mysqld datadir "$MYSQL_BASE_PATH/data/mysql${instance:+-$!instance}" $!instance)
    log=$(get_option mysqld 'log[_-]error' "/var/log/mysql$!{instance:+-$!instance}.log" $!instance)

    # Restore log, dir, perms and SELinux contexts

    if [ ! -d "$!datadir" -a ! -h "$!datadir" -a "x$(dirname "$!datadir")" = "x$MYSQL_BASE_PATH/data" ]; then
        install -d -m 0751 -omysql -gmysql "$!datadir" || exit 1
    fi

    if [ ! -e "$!log" -a ! -h "$!log" -a x$(dirname "$!log") = "x/var/log" ]; then
        case $(basename "$!log") in
            mysql*.log) install /dev/null -m0640 -omysql -gmysql "$!log" ;;
            *) ;;
        esac
    fi

    if [ -x /usr/sbin/restorecon ]; then
        /usr/sbin/restorecon "$!datadir"
        [ -e "$!log" ] && /usr/sbin/restorecon "$!log"
        for dir in $MYSQL_BASE_PATH/data/mysql-files $MYSQL_BASE_PATH/data/mysql-keyring ; do
            if [ -x /usr/sbin/semanage -a -d $MYSQL_BASE_PATH/data/mysql -a -d $!dir ] ; then
                /usr/sbin/semanage fcontext -a -e $MYSQL_BASE_PATH/data/mysql $!dir >/dev/null 2>&1
                /sbin/restorecon -r $!dir
            fi
        done
    fi

    # If special mysql dir is in place, skip db install
    [ -d "$!datadir/mysql" ] && exit 0

    # Create initial db and install validate_password plugin
    initfile="$(install_validate_password_sql_file)"
    /usr/sbin/mysqld $!{instance:+--defaults-group-suffix=@$!instance} --initialize \
                     --datadir="$!datadir" --user=mysql --init-file="$!initfile"
    rm -f "$!initfile"

    # Generate certs if needed
    if [ -x /usr/bin/mysql_ssl_rsa_setup -a ! -e "$!{datadir}/server-key.pem" ] ; then
        /usr/bin/mysql_ssl_rsa_setup --datadir="$!datadir" --uid=mysql >/dev/null 2>&1
    fi
    exit 0
}

install_db $1

exit 0